// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYCzsnP9d2ED2iZDsA2eVOZaqS-PKDKc',
    appId: '1:382990807082:web:23fea74c8944ed623d1353',
    messagingSenderId: '382990807082',
    projectId: 'tripbinapp-67491',
    authDomain: 'tripbinapp-67491.firebaseapp.com',
    storageBucket: 'tripbinapp-67491.firebasestorage.app',
    measurementId: 'G-8SEEXNHFHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKJi5rh-mH8PKKn6tUIDAmBGPS-wwf68U',
    appId: '1:382990807082:android:3dcb4d27b323e39a3d1353',
    messagingSenderId: '382990807082',
    projectId: 'tripbinapp-67491',
    storageBucket: 'tripbinapp-67491.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe7N1OietzmA3KNBkZiFeCjJcULTR8xmQ',
    appId: '1:382990807082:ios:d08d174af5a960143d1353',
    messagingSenderId: '382990807082',
    projectId: 'tripbinapp-67491',
    storageBucket: 'tripbinapp-67491.firebasestorage.app',
    iosBundleId: 'com.example.tripbinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe7N1OietzmA3KNBkZiFeCjJcULTR8xmQ',
    appId: '1:382990807082:ios:d08d174af5a960143d1353',
    messagingSenderId: '382990807082',
    projectId: 'tripbinapp-67491',
    storageBucket: 'tripbinapp-67491.firebasestorage.app',
    iosBundleId: 'com.example.tripbinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQYCzsnP9d2ED2iZDsA2eVOZaqS-PKDKc',
    appId: '1:382990807082:web:e4bad2f1251bae263d1353',
    messagingSenderId: '382990807082',
    projectId: 'tripbinapp-67491',
    authDomain: 'tripbinapp-67491.firebaseapp.com',
    storageBucket: 'tripbinapp-67491.firebasestorage.app',
    measurementId: 'G-Z80XEBTQB1',
  );
}
